name = "my-cdn-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
API_KEY = "22d-49f5-af40-c98"
ADMIN_USERNAME = "joe"
ADMIN_PASSWORD = "!monster!"
CDN_BASE_URL = "https://my-cdn-api.literalnie.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "my-cdn-db"
database_id = "6b94f653-c22d-49f5-af40-c8e269513ebb"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "my-cdn"

[dev]
port = 8787
local_protocol = "http"
